homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('tambahjadwal/', views.tambah, name='tambah'),
    path('detail/<int:index>/', views.detail, name='detail'),
    path('cekjadwal/', views.jadwal, name='jadwal'),

]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.


class Subject(models.Model):
    matkul = models.CharField('Mata Kuliah', max_length=120, null=True)
    dosen = models.CharField('Dosen', max_length=120, null=True)
    sks = models.IntegerField('Jumlah SKS', null=True)
    deskripsi = models.TextField('Keterangan', blank=True)
    semester = models.CharField(
        'Semester', max_length=120, null=True, help_text='Contoh: 1')
    kelas = models.CharField('Kelas', max_length=120, null=True)

homepage/forms.py
from django.forms import ModelForm
from .models import Subject


class SubjectForm(ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Subject
        fields = '__all__'

homepage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Subject
from .forms import SubjectForm


# Create your views here.


def index(request):
    return render(request, 'index.html')


def tambah(request):
    submitted = False
    if request.method == 'POST':
        form = SubjectForm(request.POST)
        if form.is_valid():
            form.save()
            # return render(request, 'tambah.html')
            return HttpResponseRedirect('/tambahjadwal/?submitted=True')
    else:
        form = SubjectForm()
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'tambah.html', {'form': form, 'submitted': submitted})


def detail(request, index):
    subject = Subject.objects.get(pk=index)
    return render(request, 'detail.html', {'subject': subject})


def jadwal(request):
    if request.method == "POST":
        print("LOHLAHLOH")
        Subject.objects.get(id=request.POST['id']).delete()
        return redirect('/cekjadwal/')
    list_subject = Subject.objects.all()
    return render(request, 'jadwal.html', {'subject_list': list_subject})

homepage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'style.css' %}" />
  <!-- Bootstrap CSS CDN -->
  <link rel="stylesheet" href="{% static 'bootstrap.css' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>

<body>
  <!-- Sidebar -->
  <div class="wrapper">
    {% block sidebar %}
    {% endblock %}

    {% block main_body %}
    {% endblock %}
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <script src="https://code.iconify.design/1/1.0.4/iconify.min.js"></script>

</body>

</html>

homepage/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ subject.matkul }} {% endblock %}

{% block sidebar %}
{% include 'sidebar.html' %}
{% endblock %}

{% block main_body %}
<div class="main_content">
    <section class="container-fluid d-flex flex-wrap align-content-center ">
        <div class="section-title m-auto text-center p-5">
            <h1>{{ subject.matkul }}</h1>
        </div>
        <table class="table table-bordered mx-5" style="width:90vw">
            <tbody>
                <tr>
                    <td> Dosen </td>
                    <td> {{ subject.dosen }} </td>
                </tr>

                <tr>
                    <td> Jumlah SKS </td>
                    <td> {{ subject.sks }} </td>
                </tr>

                <tr>
                    <td> Semester </td>
                    <td> {{ subject.semester }} </td>
                </tr>

                <tr>
                    <td> Kelas </td>
                    <td> {{ subject.kelas }} </td>
                </tr>

                <tr>
                    <td> Keterangan </td>
                    <td> {{ subject.deskripsi }} </td>
                </tr>
            </tbody>
        </table>
        <button class="btn btn-primary d-flex m-auto click">
            <a href="{% url 'homepage:jadwal' %}" class="text-white">
                Kembali
            </a>
        </button>
    </section>
</div>
{% endblock %}

homepage/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock %}

{% block sidebar %}
{% include 'sidebar.html' %}
{% endblock %}

{% block main_body %}
<div class="main_content">
    <div class="section-title mx-auto text-center p-5">
        <h1>Selamat datang!</h1>
    </div>
</div>
{% endblock %}

homepage/templates/jadwal.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Daftar Jadwal {% endblock %}

{% block sidebar %}
{% include 'sidebar.html' %}
{% endblock %}

{% block main_body %}
<div class="main_content">
    <section class="container-fluid d-flex flex-wrap align-content-center mb-5">
        <div class="section-title mx-auto text-center p-5">
            <h1>SUBJECT LIST</h1>
        </div>
        <table class="table table-bordered mx-5 mb-5" style="width:90vw">
            <thead class="thead-light text-center">
                <tr>
                    <th>Mata Kuliah</th>
                    <th>Dosen</th>
                    <th>Jumlah SKS</th>
                    <th>Hapus</th>
                </tr>
            </thead>
            <tbody>
                {% for x in subject_list %}
                <tr>
                    <td> <a href="/detail/{{ x.id }}">{{ x.matkul }} </a> </td>
                    <td> {{ x.dosen }} </td>
                    <td class="text-center"> {{ x.sks }} </td>
                    <td class="text-center">
                        <form method="POST" action="{% url 'homepage:jadwal' %}">
                            {% csrf_token %}
                            <input name="id" value="{{x.id}}" type="hidden">
                            <button type="submit" value="Submit" class="btn btn-primary mx-auto mt-2"
                                style="font-size: 0.8rem;">Delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <button class="btn btn-primary d-flex m-auto click">
            <a href="{% url 'homepage:tambah' %}" class="text-white">
                Tambah jadwal baru
            </a>
        </button>
    </section>
</div>

{% endblock %}

homepage/templates/sidebar.html
<div class="wrapper">
  <div class="sidebar">
    <h3>Jadwalku</h3>
    <ul>
      <li>
        <a href="{% url 'homepage:index' %}"><i class="fas fa-home"></i>Home</a>
      </li>
      <li>
        <a href="{% url 'homepage:tambah' %}"><i class="fas fa-user"></i>Tambah Mata Kuliah</a>
      </li>

      <li>
        <a href="{% url 'homepage:jadwal' %}"><i class="fas fa-project-diagram"></i>Mata Kuliah Terdaftar</a>
      </li>
    </ul>
  </div>
</div>

homepage/templates/tambah.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Tambah Jadwal {% endblock %}

{% block sidebar %}
{% include 'sidebar.html' %}
{% endblock %}

{% block main_body %}
<div class="main_content">
    <section class="container-fluid d-flex flex-wrap align-content-center ">
        {% if submitted %}
        <div class="success p-5 col-12 text-center">
            Berhasil menambah mata kuliah.
        </div>

        <button class="btn btn-primary d-flex m-auto click">
            <a href="{% url 'homepage:tambah' %}" class="text-white">
                Kembali
            </a>
        </button>
        {% else %}
        <div class="section-title mx-auto text-center p-5">
            <h1>ADD SUBJECT</h1>
        </div>

        <form action="" method="post" novalidate>
            {% csrf_token %}
            <table class="table mx-5" style="width:90vw">
                {{ form.as_table }}
                <tr>
                    <td>&nbsp;</td>
                    <td><input type="submit" value="Submit" class="btn btn-primary click"></td>
                </tr>
            </table>
        </form>
    </section>
</div>
{% endif %}

{% endblock %}